import { Resend } from 'resend';
import { config } from '../config/env';

const resend = new Resend(config.resend.apiKey);

export const sendNewsletterEmail = async (
  email: string,
  name: string,
  content: string
): Promise<boolean> => {
  try {
    const { data, error } = await resend.emails.send({
      from: 'CreatorPulse <newsletter@creatorpulse.ai>',
      to: [email],
      subject: `Your Daily Newsletter - ${new Date().toLocaleDateString()}`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Your Daily Newsletter</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 600px;
              margin: 0 auto;
              padding: 20px;
              background-color: #f8f9fa;
            }
            .container {
              background-color: white;
              border-radius: 8px;
              padding: 30px;
              box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            .header {
              text-align: center;
              border-bottom: 2px solid #e9ecef;
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            .header h1 {
              color: #2c3e50;
              margin: 0;
              font-size: 28px;
            }
            .content {
              white-space: pre-wrap;
              font-size: 16px;
              line-height: 1.8;
            }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #e9ecef;
              text-align: center;
              color: #6c757d;
              font-size: 14px;
            }
            .feedback-buttons {
              margin-top: 30px;
              text-align: center;
            }
            .feedback-btn {
              display: inline-block;
              margin: 0 10px;
              padding: 10px 20px;
              background-color: #007bff;
              color: white;
              text-decoration: none;
              border-radius: 5px;
              font-weight: bold;
            }
            .feedback-btn.negative {
              background-color: #dc3545;
            }
            .feedback-btn:hover {
              opacity: 0.9;
            }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>📰 CreatorPulse Newsletter</h1>
              <p>Hello ${name}! Here's your personalized newsletter for ${new Date().toLocaleDateString()}</p>
            </div>
            
            <div class="content">
              ${content.replace(/\n/g, '<br>')}
            </div>
            
            <div class="feedback-buttons">
              <p>How was this newsletter?</p>
              <a href="#" class="feedback-btn">👍 Helpful</a>
              <a href="#" class="feedback-btn negative">👎 Not helpful</a>
            </div>
            
            <div class="footer">
              <p>Generated by CreatorPulse AI</p>
              <p>You received this because you subscribed to CreatorPulse newsletter service.</p>
            </div>
          </div>
        </body>
        </html>
      `
    });

    if (error) {
      console.error('Error sending email:', error);
      return false;
    }

    console.log('Newsletter email sent successfully:', data);
    return true;
  } catch (error) {
    console.error('Error sending newsletter email:', error);
    return false;
  }
};

export const sendWelcomeEmail = async (email: string, name: string): Promise<boolean> => {
  try {
    const { data, error } = await resend.emails.send({
      from: 'CreatorPulse <welcome@creatorpulse.ai>',
      to: [email],
      subject: 'Welcome to CreatorPulse! 🚀',
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Welcome to CreatorPulse</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 600px;
              margin: 0 auto;
              padding: 20px;
              background-color: #f8f9fa;
            }
            .container {
              background-color: white;
              border-radius: 8px;
              padding: 30px;
              box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            .header {
              text-align: center;
              margin-bottom: 30px;
            }
            .header h1 {
              color: #2c3e50;
              margin: 0;
              font-size: 32px;
            }
            .content {
              font-size: 16px;
              line-height: 1.8;
            }
            .cta-button {
              display: inline-block;
              margin: 20px 0;
              padding: 15px 30px;
              background-color: #007bff;
              color: white;
              text-decoration: none;
              border-radius: 5px;
              font-weight: bold;
              text-align: center;
            }
            .cta-button:hover {
              opacity: 0.9;
            }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>🎉 Welcome to CreatorPulse!</h1>
            </div>
            
            <div class="content">
              <p>Hi ${name},</p>
              
              <p>Welcome to CreatorPulse, your AI-powered newsletter curation and drafting tool! We're excited to help you save time and create amazing newsletters.</p>
              
              <h3>What's next?</h3>
              <ol>
                <li><strong>Add your content sources</strong> - Connect your favorite Twitter accounts, YouTube channels, and RSS feeds</li>
                <li><strong>Upload writing samples</strong> - Help our AI learn your unique writing style</li>
                <li><strong>Generate your first newsletter</strong> - Let our AI create a personalized newsletter for you</li>
                <li><strong>Set up daily delivery</strong> - Get your newsletter delivered every morning at 8 AM</li>
              </ol>
              
              <div style="text-align: center;">
                <a href="${process.env.FRONTEND_URL || 'http://localhost:5173'}/dashboard" class="cta-button">
                  Get Started
                </a>
              </div>
              
              <p>If you have any questions, feel free to reach out to our support team.</p>
              
              <p>Happy creating!<br>The CreatorPulse Team</p>
            </div>
          </div>
        </body>
        </html>
      `
    });

    if (error) {
      console.error('Error sending welcome email:', error);
      return false;
    }

    console.log('Welcome email sent successfully:', data);
    return true;
  } catch (error) {
    console.error('Error sending welcome email:', error);
    return false;
  }
};
